# Generated by Django 5.1.1 on 2025-06-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteluser',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='hoteluser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='hoteluser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hoteluser',
            name='profile_picture',
        ),
    ]
