# Generated by Django 5.1.1 on 2025-06-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hoteluser_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelvendor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
