# Generated by Django 5.1.1 on 2025-06-21 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteluser',
            name='phone_number',
            field=models.CharField(default='9999999999', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoteluser',
            name='profile_picture',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='hotelvendor',
            name='profile_picture',
            field=models.ImageField(upload_to='profile'),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_start_date', models.DateField()),
                ('booking_end_date', models.DateField()),
                ('price', models.FloatField()),
                ('booking_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hoteluser')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.hotel')),
            ],
        ),
    ]
